[project]
name = "ha-gc-manager"
version = "0.0.2" # x-release-please-version
requires-python = ">=3.14.2"
dependencies = []

[dependency-groups]
test = [
  "pytest-homeassistant-custom-component>=0.13.323",
]
dev = [
  { include-group = "test" },
  "mypy>=1.20.0",
]

[tool.mypy]
mypy_path = ["custom_components"]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.uv]
required-version = "==0.13.0"
package = false
